package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * BancoId generated by hbm2java
 */
public class BancoId  implements java.io.Serializable {


	private int numeroCuenta;
	private int clienteCedula;

	public BancoId() {
	}

	public BancoId(int numeroCuenta, int clienteCedula) {
		this.numeroCuenta = numeroCuenta;
		this.clienteCedula = clienteCedula;
	}

	public int getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(int numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}
	public int getClienteCedula() {
		return this.clienteCedula;
	}

	public void setClienteCedula(int clienteCedula) {
		this.clienteCedula = clienteCedula;
	}


	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof BancoId) ) return false;
		BancoId castOther = ( BancoId ) other; 

		return (this.getNumeroCuenta()==castOther.getNumeroCuenta())
				&& (this.getClienteCedula()==castOther.getClienteCedula());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumeroCuenta();
		result = 37 * result + this.getClienteCedula();
		return result;
	}   

	public int obtenerId(){
		return Integer.parseInt(this.getNumeroCuenta()+""+this.getClienteCedula());
	}

}


