package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1

/**
 * Banco generated by hbm2java
 */
public class Banco  implements java.io.Serializable {


     private BancoId id;
     private double saldo;
     private String nombreBanco;

    public Banco() {
    }

	
    public Banco(BancoId id, double saldo) {
        this.id = id;
        this.saldo = saldo;
    }
    public Banco(BancoId id, double saldo, String nombreBanco) {
       this.id = id;
       this.saldo = saldo;
       this.nombreBanco = nombreBanco;
    }
   
    public BancoId getId() {
        return this.id;
    }
    
    public void setId(BancoId id) {
        this.id = id;
    }
    public double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }
    public String getNombreBanco() {
        return this.nombreBanco;
    }
    
    public void setNombreBanco(String nombreBanco) {
        this.nombreBanco = nombreBanco;
    }

}


