package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

/**
 * CamaraComercio generated by hbm2java
 */
public class CamaraComercio  implements java.io.Serializable {


	private int nitComercio;
	private int valorNegocio;
	private String fechaPagoComercio;
	private double pagoCamaraComercio;

	public CamaraComercio() {

	}

	public CamaraComercio(int nitComercio, int valorNegocio, String fechaPagoComercio, double pagoCamaraComercio) {
		this.nitComercio = nitComercio;
		this.valorNegocio = valorNegocio;
		this.fechaPagoComercio = fechaPagoComercio;
		this.pagoCamaraComercio = pagoCamaraComercio;
	}

	public int getNitComercio() {
		return this.nitComercio;
	}

	public void setNitComercio(int nitComercio) {
		this.nitComercio = nitComercio;
	}
	public int getValorNegocio() {
		return this.valorNegocio;
	}

	public void setValorNegocio(int valorNegocio) {
		this.valorNegocio = valorNegocio;
	}
	public String getFechaPagoComercio() {
		return this.fechaPagoComercio;
	}

	public void setFechaPagoComercio(String fechaPagoComercio) {
		this.fechaPagoComercio = fechaPagoComercio;
	}
	public double getPagoCamaraComercio() {
		return this.pagoCamaraComercio;
	}

	public void setPagoCamaraComercio(double pagoCamaraComercio) {
		this.pagoCamaraComercio = pagoCamaraComercio;
	}
}


