package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * CreditoLuzId generated by hbm2java
 */
public class CreditoLuzId  implements java.io.Serializable {


     private int contratoLuz;
     private int ELuzNReciboLuz;

    public CreditoLuzId() {
    }

    public CreditoLuzId(int contratoLuz, int ELuzNReciboLuz) {
       this.contratoLuz = contratoLuz;
       this.ELuzNReciboLuz = ELuzNReciboLuz;
    }
   
    public int getContratoLuz() {
        return this.contratoLuz;
    }
    
    public void setContratoLuz(int contratoLuz) {
        this.contratoLuz = contratoLuz;
    }
    public int getELuzNReciboLuz() {
        return this.ELuzNReciboLuz;
    }
    
    public void setELuzNReciboLuz(int ELuzNReciboLuz) {
        this.ELuzNReciboLuz = ELuzNReciboLuz;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CreditoLuzId) ) return false;
		 CreditoLuzId castOther = ( CreditoLuzId ) other; 
         
		 return (this.getContratoLuz()==castOther.getContratoLuz())
 && (this.getELuzNReciboLuz()==castOther.getELuzNReciboLuz());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContratoLuz();
         result = 37 * result + this.getELuzNReciboLuz();
         return result;
   }   


}


