package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * CreditoLuz generated by hbm2java
 */
public class CreditoLuz  implements java.io.Serializable {


     private CreditoLuzId id;
     private double valorElectro;
     private String detalleContratoluz;

    public CreditoLuz() {
    }

	
    public CreditoLuz(CreditoLuzId id, double valorElectro) {
        this.id = id;
        this.valorElectro = valorElectro;
    }
    public CreditoLuz(CreditoLuzId id, double valorElectro, String detalleContratoluz) {
       this.id = id;
       this.valorElectro = valorElectro;
       this.detalleContratoluz = detalleContratoluz;
    }
   
    public CreditoLuzId getId() {
        return this.id;
    }
    
    public void setId(CreditoLuzId id) {
        this.id = id;
    }
    public double getValorElectro() {
        return this.valorElectro;
    }
    
    public void setValorElectro(double valorElectro) {
        this.valorElectro = valorElectro;
    }
    public String getDetalleContratoluz() {
        return this.detalleContratoluz;
    }
    
    public void setDetalleContratoluz(String detalleContratoluz) {
        this.detalleContratoluz = detalleContratoluz;
    }




}


