package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * DetalleSoatId generated by hbm2java
 */
public class DetalleSoatId  implements java.io.Serializable {


     private int clienteCedula;
     private String soatNPlaca;

    public DetalleSoatId() {
    }

    public DetalleSoatId(int clienteCedula, String soatNPlaca) {
       this.clienteCedula = clienteCedula;
       this.soatNPlaca = soatNPlaca;
    }
   
    public int getClienteCedula() {
        return this.clienteCedula;
    }
    
    public void setClienteCedula(int clienteCedula) {
        this.clienteCedula = clienteCedula;
    }
    public String getSoatNPlaca() {
        return this.soatNPlaca;
    }
    
    public void setSoatNPlaca(String soatNPlaca) {
        this.soatNPlaca = soatNPlaca;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleSoatId) ) return false;
		 DetalleSoatId castOther = ( DetalleSoatId ) other; 
         
		 return (this.getClienteCedula()==castOther.getClienteCedula())
 && ( (this.getSoatNPlaca()==castOther.getSoatNPlaca()) || ( this.getSoatNPlaca()!=null && castOther.getSoatNPlaca()!=null && this.getSoatNPlaca().equals(castOther.getSoatNPlaca()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClienteCedula();
         result = 37 * result + ( getSoatNPlaca() == null ? 0 : this.getSoatNPlaca().hashCode() );
         return result;
   }   


}


