package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * DetalleCamaraId generated by hbm2java
 */
public class DetalleCamaraId  implements java.io.Serializable {


     private int clienteCedula;
     private int camaraComercioNitCamaraComercio;

    public DetalleCamaraId() {
    }

    public DetalleCamaraId(int clienteCedula, int camaraComercioNitCamaraComercio) {
       this.clienteCedula = clienteCedula;
       this.camaraComercioNitCamaraComercio = camaraComercioNitCamaraComercio;
    }
   
    public int getClienteCedula() {
        return this.clienteCedula;
    }
    
    public void setClienteCedula(int clienteCedula) {
        this.clienteCedula = clienteCedula;
    }
    public int getCamaraComercioNitCamaraComercio() {
        return this.camaraComercioNitCamaraComercio;
    }
    
    public void setCamaraComercioNitCamaraComercio(int camaraComercioNitCamaraComercio) {
        this.camaraComercioNitCamaraComercio = camaraComercioNitCamaraComercio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleCamaraId) ) return false;
		 DetalleCamaraId castOther = ( DetalleCamaraId ) other; 
         
		 return (this.getClienteCedula()==castOther.getClienteCedula())
 && (this.getCamaraComercioNitCamaraComercio()==castOther.getCamaraComercioNitCamaraComercio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClienteCedula();
         result = 37 * result + this.getCamaraComercioNitCamaraComercio();
         return result;
   }   


}


