package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * DetallePredioId generated by hbm2java
 */
public class DetallePredioId  implements java.io.Serializable {


     private int clienteCedula;
     private int impuestoPredialNPredio;

    public DetallePredioId() {
    }

    public DetallePredioId(int clienteCedula, int impuestoPredialNPredio) {
       this.clienteCedula = clienteCedula;
       this.impuestoPredialNPredio = impuestoPredialNPredio;
    }
   
    public int getClienteCedula() {
        return this.clienteCedula;
    }
    
    public void setClienteCedula(int clienteCedula) {
        this.clienteCedula = clienteCedula;
    }
    public int getImpuestoPredialNPredio() {
        return this.impuestoPredialNPredio;
    }
    
    public void setImpuestoPredialNPredio(int impuestoPredialNPredio) {
        this.impuestoPredialNPredio = impuestoPredialNPredio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallePredioId) ) return false;
		 DetallePredioId castOther = ( DetallePredioId ) other; 
         
		 return (this.getClienteCedula()==castOther.getClienteCedula())
 && (this.getImpuestoPredialNPredio()==castOther.getImpuestoPredialNPredio());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getClienteCedula();
         result = 37 * result + this.getImpuestoPredialNPredio();
         return result;
   }   


}


