package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * DetalleSoat generated by hbm2java
 */
public class DetalleSoat  implements java.io.Serializable {


     private DetalleSoatId id;
     private String detalleSoat;

    public DetalleSoat() {
    }

	
    public DetalleSoat(DetalleSoatId id) {
        this.id = id;
    }
    public DetalleSoat(DetalleSoatId id, String detalleSoat) {
       this.id = id;
       this.detalleSoat = detalleSoat;
    }
   
    public DetalleSoatId getId() {
        return this.id;
    }
    
    public void setId(DetalleSoatId id) {
        this.id = id;
    }
    public String getDetalleSoat() {
        return this.detalleSoat;
    }
    
    public void setDetalleSoat(String detalleSoat) {
        this.detalleSoat = detalleSoat;
    }




}


