package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * DetalleCamara generated by hbm2java
 */
public class DetalleCamara  implements java.io.Serializable {


     private DetalleCamaraId id;
     private String descripcionNegocio;

    public DetalleCamara() {
    }

	
    public DetalleCamara(DetalleCamaraId id) {
        this.id = id;
    }
    public DetalleCamara(DetalleCamaraId id, String descripcionNegocio) {
       this.id = id;
       this.descripcionNegocio = descripcionNegocio;
    }
   
    public DetalleCamaraId getId() {
        return this.id;
    }
    
    public void setId(DetalleCamaraId id) {
        this.id = id;
    }
    public String getDescripcionNegocio() {
        return this.descripcionNegocio;
    }
    
    public void setDescripcionNegocio(String descripcionNegocio) {
        this.descripcionNegocio = descripcionNegocio;
    }




}


