package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * EAguaId generated by hbm2java
 */
public class EAguaId  implements java.io.Serializable {


	private int reciboAgua;
	private int clienteCedula;

	public EAguaId() {
	}

	public EAguaId(int reciboAgua, int clienteCedula) {
		this.reciboAgua = reciboAgua;
		this.clienteCedula = clienteCedula;
	}

	public int getReciboAgua() {
		return this.reciboAgua;
	}

	public void setReciboAgua(int reciboAgua) {
		this.reciboAgua = reciboAgua;
	}
	public int getClienteCedula() {
		return this.clienteCedula;
	}

	public void setClienteCedula(int clienteCedula) {
		this.clienteCedula = clienteCedula;
	}


	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof EAguaId) ) return false;
		EAguaId castOther = ( EAguaId ) other; 

		return (this.getReciboAgua()==castOther.getReciboAgua())
				&& (this.getClienteCedula()==castOther.getClienteCedula());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReciboAgua();
		result = 37 * result + this.getClienteCedula();
		return result;
	}   
	
	public int obtenerId(){
		return Integer.parseInt(this.getReciboAgua()+""+this.getClienteCedula());
	}


}


