package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * EGas generated by hbm2java
 */
public class EGas  implements java.io.Serializable {


     private EGasId id;
     private String fechaPagoGas;
     private double valorGas;
     private String detalleGas;

    public EGas() {
    	
    }

	
    public EGas(EGasId id, String fechaPagoGas, double valorGas) {
        this.id = id;
        this.fechaPagoGas = fechaPagoGas;
        this.valorGas = valorGas;
    }
    public EGas(EGasId id, String fechaPagoGas, double valorGas, String detalleGas) {
       this.id = id;
       this.fechaPagoGas = fechaPagoGas;
       this.valorGas = valorGas;
       this.detalleGas = detalleGas;
    }
   
    public EGasId getId() {
        return this.id;
    }
    
    public void setId(EGasId id) {
        this.id = id;
    }
    public String getFechaPagoGas() {
        return this.fechaPagoGas;
    }
    
    public void setFechaPagoGas(String fechaPagoGas) {
        this.fechaPagoGas = fechaPagoGas;
    }
    public double getValorGas() {
        return this.valorGas;
    }
    
    public void setValorGas(double valorGas) {
        this.valorGas = valorGas;
    }
    public String getDetalleGas() {
        return this.detalleGas;
    }
    
    public void setDetalleGas(String detalleGas) {
        this.detalleGas = detalleGas;
    }




}


