package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * EGasId generated by hbm2java
 */
public class EGasId  implements java.io.Serializable {


     private int reciboGas;
     private int clienteCedula;

    public EGasId() {
    }

    public EGasId(int reciboGas, int clienteCedula) {
       this.reciboGas = reciboGas;
       this.clienteCedula = clienteCedula;
    }
   
    public int getReciboGas() {
        return this.reciboGas;
    }
    
    public void setReciboGas(int reciboGas) {
        this.reciboGas = reciboGas;
    }
    public int getClienteCedula() {
        return this.clienteCedula;
    }
    
    public void setClienteCedula(int clienteCedula) {
        this.clienteCedula = clienteCedula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EGasId) ) return false;
		 EGasId castOther = ( EGasId ) other; 
         
		 return (this.getReciboGas()==castOther.getReciboGas())
 && (this.getClienteCedula()==castOther.getClienteCedula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getReciboGas();
         result = 37 * result + this.getClienteCedula();
         return result;
   }   


}


