package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InternetTv generated by hbm2java
 */
public class InternetTv  implements java.io.Serializable {


     private InternetTvId id;
     private Date fechaPagoInternet;
     private double valorInternet;
     private String detallerInternet;

    public InternetTv() {
    }

	
    public InternetTv(InternetTvId id, Date fechaPagoInternet, double valorInternet) {
        this.id = id;
        this.fechaPagoInternet = fechaPagoInternet;
        this.valorInternet = valorInternet;
    }
    public InternetTv(InternetTvId id, Date fechaPagoInternet, double valorInternet, String detallerInternet) {
       this.id = id;
       this.fechaPagoInternet = fechaPagoInternet;
       this.valorInternet = valorInternet;
       this.detallerInternet = detallerInternet;
    }
   
    public InternetTvId getId() {
        return this.id;
    }
    
    public void setId(InternetTvId id) {
        this.id = id;
    }
    public Date getFechaPagoInternet() {
        return this.fechaPagoInternet;
    }
    
    public void setFechaPagoInternet(Date fechaPagoInternet) {
        this.fechaPagoInternet = fechaPagoInternet;
    }
    public double getValorInternet() {
        return this.valorInternet;
    }
    
    public void setValorInternet(double valorInternet) {
        this.valorInternet = valorInternet;
    }
    public String getDetallerInternet() {
        return this.detallerInternet;
    }
    
    public void setDetallerInternet(String detallerInternet) {
        this.detallerInternet = detallerInternet;
    }




}


