package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * TelefoniaId generated by hbm2java
 */
public class TelefoniaId  implements java.io.Serializable {


     private int reciboTelefono;
     private int clienteCedula;

    public TelefoniaId() {
    }

    public TelefoniaId(int reciboTelefono, int clienteCedula) {
       this.reciboTelefono = reciboTelefono;
       this.clienteCedula = clienteCedula;
    }
   
    public int getReciboTelefono() {
        return this.reciboTelefono;
    }
    
    public void setReciboTelefono(int reciboTelefono) {
        this.reciboTelefono = reciboTelefono;
    }
    public int getClienteCedula() {
        return this.clienteCedula;
    }
    
    public void setClienteCedula(int clienteCedula) {
        this.clienteCedula = clienteCedula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefoniaId) ) return false;
		 TelefoniaId castOther = ( TelefoniaId ) other; 
         
		 return (this.getReciboTelefono()==castOther.getReciboTelefono())
 && (this.getClienteCedula()==castOther.getClienteCedula());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getReciboTelefono();
         result = 37 * result + this.getClienteCedula();
         return result;
   }   


}


