package logica;
// Generated 18/04/2015 08:11:28 PM by Hibernate Tools 4.3.1



/**
 * Telefonia generated by hbm2java
 */
public class Telefonia  implements java.io.Serializable {


     private TelefoniaId id;
     private String fechaPagoTelefonia;
     private int valorTelefonia;
     private String detalleTelefonia;

    public Telefonia() {
    }

	
    public Telefonia(TelefoniaId id, String fechaPagoTelefonia, int valorTelefonia) {
        this.id = id;
        this.fechaPagoTelefonia = fechaPagoTelefonia;
        this.valorTelefonia = valorTelefonia;
    }
    public Telefonia(TelefoniaId id, String fechaPagoTelefonia, int valorTelefonia, String detalleTelefonia) {
       this.id = id;
       this.fechaPagoTelefonia = fechaPagoTelefonia;
       this.valorTelefonia = valorTelefonia;
       this.detalleTelefonia = detalleTelefonia;
    }
   
    public TelefoniaId getId() {
        return this.id;
    }
    
    public void setId(TelefoniaId id) {
        this.id = id;
    }
    public String getFechaPagoTelefonia() {
        return this.fechaPagoTelefonia;
    }
    
    public void setFechaPagoTelefonia(String fechaPagoTelefonia) {
        this.fechaPagoTelefonia = fechaPagoTelefonia;
    }
    public int getValorTelefonia() {
        return this.valorTelefonia;
    }
    
    public void setValorTelefonia(int valorTelefonia) {
        this.valorTelefonia = valorTelefonia;
    }
    public String getDetalleTelefonia() {
        return this.detalleTelefonia;
    }
    
    public void setDetalleTelefonia(String detalleTelefonia) {
        this.detalleTelefonia = detalleTelefonia;
    }
}


